---
# tasks file for roles/radius
- name: install svc radius
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{svc.radius.pkg}}"

- name: starting radius service
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - "{{ svc.radius.deamon }}"